Repository Elochukwu3/100daysofcoding, pull requests merged in 2024-09, with the labels that each got.

#4 added the enums
  src/modules/common/enums/StatusCodes.ts
Labels: enhancement

#5 [Ft #108]: verify-otp
  package.json
  src/modules/auth/controllers/verifyOtp.ts
  src/modules/auth/routes/auth.routes.ts
Labels: good first issue

#8 Fx #107 get otp
  package-lock.json
  package.json
  src/app.ts
  src/modules/auth/controllers/getOtp.ts
  src/modules/auth/controllers/registerController.ts
  src/modules/auth/controllers/verifyOtp.ts
  src/modules/auth/routes/auth.routes.ts
  src/modules/auth/utils/generateOtp.ts
  src/modules/common/config/db.config.ts
  src/modules/common/utils/sendEmail.ts
  src/modules/interfaces/User.ts
Labels: bug

#10 Fx #107 otp
  src/app.ts
  src/modules/auth/controllers/refreshToken.ts
  src/modules/auth/controllers/registerController.ts
  src/modules/auth/controllers/verifyOtp.ts
  src/modules/auth/models/User.ts
  src/modules/interfaces/User.ts
  src/modules/interfaces/session.ts
  tsconfig.json
Labels: enhancement

#14 ADD: api key function
  src/app.ts
  src/modules/auth/controllers/getOtp.ts
  src/modules/common/middlewares/apiKey.ts
Labels: enhancement

#16 error: debugging production error
  src/modules/auth/controllers/verifyOtp.ts
Labels: bug
